version: '3.8'
services:
  redis-node1:
    image: redis:latest
    container_name: redis_cluster1
    command: redis-server --port 7001 --cluster-enabled yes --cluster-config-file nodes.conf --appendonly yes --requirepass "123456" --masterauth "123456"
    ports:
      - "7001:7001"
      - "17001:17001" # Cluster bus port

  redis-node2:
    image: redis:latest
    container_name: redis_cluster2
    command: redis-server --port 7002 --cluster-enabled yes --cluster-config-file nodes.conf --appendonly yes --requirepass "123456" --masterauth "123456"
    ports:
      - "7002:7002"
      - "17002:17002" # Cluster bus port

  # 为构成最小集群（3主3从），至少需要6个节点
  # 为简化示例，这里只创建两个节点，并由 cluster-creator 将它们组成一个最小主从集群
  # 注意：实际生产环境至少需要3个主节点

  redis-cluster-creator:
    image: redis:latest
    container_name: redis_cluster_creator
    command: >
      bash -c "sleep 5 && \
               redis-cli -a 123456 --cluster create host.docker.internal:7001 host.docker.internal:7002 --cluster-replicas 0 --cluster-yes"
    depends_on:
      - redis-node1
      - redis-node2